1. Create a null vector of size 10 but the fifth value which is 1 

2. Create a vector with values ranging from 10 to 49

3. Reverse a vector

4. Create a 3x3 matrix with values ranging from 0 to 8

5. Find indices of non-zero elements from [1,2,0,0,4,0]

6. Create a 3x3x3 array with random values

7. Create a 10x10 array with random values and find the minimum and maximum values

8. Create a 2d array with 1 on the border and 0 inside


In [38]:
import numpy as np

In [39]:
# 1. Create a null vector of size 10 but the fifth value which is 1
aa = np.zeros((10,))
aa[4] = 1
print(aa)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [40]:
# 2. Create a vector with values ranging from 10 to 49
bb = np.array([i for i in range(10, 50)])
print(bb)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [41]:
# 3. Reverse a vector
print(bb[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [42]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8
cc = np.array([i for i in range(9)])
cc = cc.reshape((3,3))
print(cc)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
# 5. Find indices of non-zero elements from [1,2,0,0,4,0]
dd_temp = [1,2,0,0,4,0]
dd = np.array([dd_temp.index(i) for i in dd_temp if i!=0])
print(dd)

[0 1 4]


In [44]:
# 6. Create a 3x3x3 array with random values
np.random.seed(100)
ee = np.random.randint(0,100,size=(3,3,3))
print(ee)

[[[ 8 24 67]
  [87 79 48]
  [10 94 52]]

 [[98 53 66]
  [98 14 34]
  [24 15 60]]

 [[58 16  9]
  [93 86  2]
  [27  4 31]]]


In [45]:
# 7. Create a 10x10 array with random values and find the minimum and maximum values
np.random.seed(100)
ff = np.random.randint(0,100,size=(10,10))
print(ff)
print("max value: ",ff.max())
print("min value: ",ff.min())

[[ 8 24 67 87 79 48 10 94 52 98]
 [53 66 98 14 34 24 15 60 58 16]
 [ 9 93 86  2 27  4 31  1 13 83]
 [ 4 91 59 67  7 49 47 65 61 14]
 [55 71 80  2 94 19 98 63 53 27]
 [56 30 48 47 39 38 44 18 64 56]
 [34 53 74 17 72 13 30 17 53 68]
 [50 91 91 83 53 78  0 13 57 76]
 [ 3 70  3 84 79 10 87 60  3 48]
 [52 43 36  5 71 38 86 94 98 42]]
max value:  98
min value:  0


In [46]:
# 8. Create a 2d array with 1 on the border and 0 inside
gg = np.zeros((10,10))
for i in range(gg.shape[0]):
    for j in range(gg.shape[1]):
        if(i==0 or j==0 or i==gg.shape[0]-1 or j==gg.shape[1]-1):
            gg[i][j] = 1
print(gg)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
